name: task-teste-two
description: This is another test task that echos to console
inputs:
- label: Commit message
  type: text
  default: example
  name: message
  cache: true
  required: true
  global_input: false
supported-os:
- windows
- linux
- mac
requirements-check:
  dependency-example:
    check-command: nothing --version
    info: nothing is not installed
command: echo "Hello from task two"
