name: task-for-mac
description: This task should only run on mac
inputs:
- label: Commit message
  type: text
  default: example
  name: message
  cache: true
  required: 'true'
  global_input: false
supported-os:
- mac
requirements-check:
  dependency-example:
    check-command: git --version
    info: git is not installed
command: echo "running on macos"
