name: local-plugin-to-delete
description: PLugin to be used in delete plugin integration test
types:
  - app
inputs:
  - label: Input Example
    type: text
    name: example
    default: any text
  - label: Example of number
    type: int
    name: any_number
    default: "10"
  - label: Example of list
    type: multiselect
    name: any_list
    items:
      - item1
      - item2
