name: task-docker
description: Run task using docker container
container:
  image: alpine:3.16.2
  volumes:
    - "{{ component_path.absolute() }}:/data"
supported-os:
- windows
- linux
- mac
requirements-check:
  dependency-example:
    check-command: docker --version
    info: docker is not installed
command: |
  apk --version
  cd data
  ls
